# Generated by Django 5.1.3 on 2025-06-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolestatus',
            table='role_status',
        ),
    ]
