# Generated by Django 5.1.3 on 2025-04-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left_ms', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
