# Generated by Django 5.1.3 on 2025-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_portal_additionalbenefit',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='job_portal_department',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='job_portal_language',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='job_portal_qualification',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='job_portal_requiredskill',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
