# Generated by Django 5.1.3 on 2025-10-06 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_job_portal_additionalbenefit_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('upload_type', models.CharField(choices=[('bulk_exam', 'Bulk Exam Upload'), ('single_subject', 'Single Subject Exam Upload')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_file_uploads', to='super_admin.university')),
            ],
            options={
                'db_table': 'exam_file_uploads',
                'unique_together': {('university', 'file_hash', 'upload_type')},
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination', to='super_admin.examfileupload'),
        ),
        migrations.AddField(
            model_name='questions',
            name='excel_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='super_admin.examfileupload'),
        ),
    ]
