# Generated by Django 5.1.3 on 2025-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_alter_rolestatus_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Lead_Label_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'common_lead_labels_tags',
            },
        ),
        migrations.DeleteModel(
            name='Common_Lead_Label',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='phonecode',
        ),
    ]
