# Generated by Django 5.1.3 on 2025-06-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
