# Generated by Django 5.1.3 on 2025-10-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_examfileupload_examination_excel_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'student_file_uploads',
                'indexes': [models.Index(fields=['file_name'], name='student_fil_file_na_ff1f99_idx')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='super_admin.studentfileupload'),
        ),
    ]
