# Generated by Django 5.1.3 on 2025-05-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source',
                'ordering': ['-created_at'],
            },
        ),
    ]
