# Generated by Django 5.1.3 on 2025-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_studentfileupload_student_student_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
