# Generated by Django 5.1.3 on 2025-10-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_alter_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_admin.states'),
        ),
    ]
