# Generated by Django 5.1.3 on 2025-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_leads_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreciept',
            name='payment_transactionID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
