# Generated by Django 5.1.3 on 2025-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_paymentreciept_payment_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalenrollmentdetails',
            name='enrolled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
