# Generated by Django 5.1.3 on 2025-05-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_remove_studentexaminationtime_examdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedexamination',
            name='examdetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='super_admin.studentappearingexam'),
        ),
    ]
