# Generated by Django 5.1.3 on 2025-10-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_additionalenrollmentdetails_enrolled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_pending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PendingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_university_enrollment', models.CharField(blank=True, max_length=20, null=True)),
                ('student_university_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('student_university_password', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.student')),
            ],
            options={
                'db_table': 'pending_verification',
            },
        ),
    ]
