# Generated by Django 5.1.3 on 2025-05-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_submittedexamination_examdetails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('student', 'exam', 'examdetails')},
        ),
    ]
