# Generated by Django 5.1.3 on 2025-10-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0009_student_is_pending_pendingverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
