# Generated by Django 5.1.3 on 2025-10-31 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_student_is_approve_alter_student_is_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_PaymentReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_categories', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('fee_reciept_type', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('semyearfees', models.CharField(blank=True, max_length=10, null=True)),
                ('paidamount', models.CharField(blank=True, max_length=10, null=True)),
                ('pendingamount', models.CharField(blank=True, max_length=10, null=True)),
                ('advanceamount', models.CharField(blank=True, max_length=10, null=True)),
                ('transactiontime', models.DateTimeField(auto_now=True)),
                ('transactionID', models.CharField(max_length=50)),
                ('payment_transactionID', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentmode', models.CharField(default='Online', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('semyear', models.CharField(blank=True, max_length=10, null=True)),
                ('uncleared_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.student')),
            ],
            options={
                'db_table': 'additional_paymentreciept',
            },
        ),
    ]
