# Generated by Django 5.1.3 on 2025-10-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0011_additional_paymentreciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_paymentreciept',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='additional_receipts/'),
        ),
    ]
