# Generated by Django 5.1.3 on 2025-11-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0012_additional_paymentreciept_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuploaded',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='university_result/'),
        ),
        migrations.AlterField(
            model_name='resultuploaded',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultuploaded',
            name='examination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultuploaded',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resultuploaded',
            name='semyear',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resultuploaded',
            name='uploaded',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UniversityReregistrtationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('examination', models.CharField(blank=True, max_length=100, null=True)),
                ('semester_year', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='university_fees/')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_reregistration_fees', to='super_admin.student')),
            ],
            options={
                'db_table': 'UniversityReregistrtationFee',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
