# Generated by Django 5.1.3 on 2025-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0013_resultuploaded_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldocuments',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='personal_documents/'),
        ),
    ]
