# Generated by Django 5.1.3 on 2025-11-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0014_personaldocuments_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=100)),
                ('sem_year', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('file_field', models.FileField(upload_to='student_forms/')),
                ('form_type', models.CharField(choices=[('self_assessment', 'Self Assessment Form'), ('teacher_assessment', 'Teacher Assessment Form'), ('assignment_assessment', 'Assignment Assessment Form'), ('industrial_assessment', 'Industrial Assessment Form'), ('guardian_assessment', 'Guardian Assessment Form')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_assessment_form',
                'unique_together': {('student_id', 'sem_year', 'form_type')},
            },
        ),
    ]
