# Generated by Django 5.1.3 on 2025-11-12 12:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0016_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('local_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('google_drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_link', models.URLField(blank=True, null=True)),
                ('drive_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Direct audio playback URL', null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('play_count', models.IntegerField(default=0, help_text='Number of times played')),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded to Drive'), ('failed', 'Upload Failed'), ('synced', 'Synced from Drive')], default='pending', max_length=20)),
                ('upload_attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording_date', models.DateTimeField(default=datetime.datetime.now)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_recording',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drive_folder',
            },
        ),
        migrations.CreateModel(
            name='PlaybackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.callrecording')),
            ],
            options={
                'db_table': 'playback_log',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_started_at', models.DateTimeField(auto_now_add=True)),
                ('sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files_found', models.IntegerField(default=0)),
                ('new_files_added', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.drivefolder')),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['-sync_started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['phone_number'], name='call_record_phone_n_a09b74_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['status'], name='call_record_status_dfacb3_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['recording_date'], name='call_record_recordi_8e1a3f_idx'),
        ),
    ]
