# Generated by Django 5.1.3 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0017_callrecording_drivefolder_playbacklog_synclog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
