# Generated by Django 5.1.3 on 2025-11-13 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0018_alter_callrecording_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='recording_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
