# Generated by Django 5.1.3 on 2025-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0019_callrecording_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='phonecode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
